ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7pop
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7pop/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7pop/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7pop/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
