ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7poplte
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7poplte/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7poplte/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7poplte/common
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
