ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7poplte/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7poplte
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7poplte/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7poplte/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_led_flash.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_trigger.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_i2c_trigger.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_torch.o
obj-$(CONFIG_MSMB_CAMERA) += msm_flash.o

