ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7poplte
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7poplte/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7poplte/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7poplte/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
