ccflags-y += -Idrivers/media/platform/msm/camera_v2_c7lte
ccflags-y += -Idrivers/media/platform/msm/camera_v2_c7lte/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_c7lte/sensor/io
obj-$(CONFIG_MSM_CSIPHY) += msm_csiphy.o
