ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7pop
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7pop/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7pop/sensor/io
obj-$(CONFIG_MSM_CSID) += msm_csid.o
