ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7pop/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7pop
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7pop/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7pop/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_led_flash.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_trigger.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_i2c_trigger.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_torch.o
obj-$(CONFIG_MSMB_CAMERA) += msm_flash.o

