ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7poplte
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7poplte/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7poplte/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7poplte/sensor/cci
ifdef CONFIG_USE_CAMERA_HW_BIG_DATA
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7poplte/sensor
endif
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
