ccflags-y += -Idrivers/media/platform/msm/camera_v2_c7lte
ccflags-y += -Idrivers/media/platform/msm/camera_v2_c7lte/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_c7lte/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_c7lte/common
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
