ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7pop
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7pop/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7pop/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7pop/common
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
