ccflags-y += -Idrivers/media/platform/msm/camera_v2_c7lte
ccflags-y += -Idrivers/media/platform/msm/camera_v2_c7lte/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_c7lte/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_c7lte/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_ois.o
