ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7pop
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7pop/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7pop/msm_vb2
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7pop/camera
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7pop/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7pop/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += cci/ io/ csiphy/ csid/ actuator/ eeprom/ ois/ flash/
obj-$(CONFIG_MSM_CAMERA_SENSOR) += msm_sensor_init.o msm_sensor_driver.o msm_sensor.o
