ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7poplte
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7poplte/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7poplte/msm_vb2
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7poplte/camera
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7poplte/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j7poplte/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += cci/ io/ csiphy/ csid/ actuator/ eeprom/ ois/ flash/
obj-$(CONFIG_MSM_CAMERA_SENSOR) += msm_sensor_init.o msm_sensor_driver.o msm_sensor.o
